name: Deploy and Scale Kubernetes Application

on:
  push:
    branches:
      - main  # Trigger the workflow on push events to the main branch.
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests targeted at the main branch.

jobs:
  deployment:
    runs-on: ubuntu-latest  # Specifies the runner environment.
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checks out your repository under $GITHUB_WORKSPACE, so your workflow can access it.

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v1  # Sets up kubectl CLI on the runner.
        with:
          version: 'latest'  # Optionally specify a specific version of kubectl, if needed.

      - name: Deploy
        run: |
          kubectl apply -f deployment1.yaml
          kubectl apply -f deployment2.yaml
          kubectl apply -f service.yaml

      - name: Scale Deployments
        run: |
          kubectl scale deployment/python-app-v1 --replicas=9
          kubectl scale deployment/python-app-v2 --replicas=1
